[profile.default]
src = "contracts"
out = "out"
optimizer = true
optimizer_runs = 200 # Set the number of optimization runs
# yul = true
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts@v4.9.0=node_modules/@openzeppelin/contracts',
    '@openzeppelin/contracts-upgradeable@v4.9.0=node_modules/@openzeppelin/contracts-upgradeable',
    '@openzeppelin/contracts=node_modules/@openzeppelin/contracts'
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options